version: '3'
services: 
    postgres:
        image: 'postgres:10'
        environment:
            POSTGRES_PASSWORD: password
    api:
        build:
            dockerfile: Dockerfile.dev
            context: ./server
        volumes: 
            - /app/node_modules 
            - ./server:/app
        environment: 
            - PGUSER=postgres
            - PGHOST=postgres
            - PGDATABASE=postgres
            - PGPASSWORD=password
            - PGPORT=5432
        # ports: 
        #     - "5000:5000"

    client:
        stdin_open: true
        build:
            dockerfile: Dockerfile.dev
            context: ./client
        volumes:
            - /app/node_modules
            - ./client:/app
    
    proxy_server:
        restart: always
        build: 
            dockerfile: Dockerfile.dev
            context: ./nginx
        ports: 
            - "4000:80"
